apiVersion: v1
kind: Service
metadata:
  labels:
    app: chartx
    app.kubernetes.io/managed-by: Helm
  name: chartx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: chartx
